name: avnon_pre_interview
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.3.3
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  injectable: ^2.3.2
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.3
  rxdart: ^0.27.7
  uuid: ^4.2.2
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # contains Isar Core
  auto_size_text: ^3.0.0
  gap: ^3.0.1
  event_bus: ^2.0.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  collection: ^1.18.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_gen_runner: any
  auto_route_generator: any
  injectable_generator: any
  json_serializable: ^6.7.1
  freezed: ^2.4.3
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  isar_generator: ^3.1.0+1
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.7
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen/
  use_deferred_loading: false
